main: me.arrow.Core
name: ArrowLoader
version: 0.4.0
load: POSTWORLD
description: Loader for Arrow Anticheat (stel9178 on discord)
author: Stel
api-version: 1.13
folia-supported: true
softdepend:
  - PacketEvents
commands:
  arrow:
    description: The main anticheat command!
  updatearrow:
    description: Reload the Arrow anticheat core without server restart
    permission: arrow.admin
permissions:
  arrow.admin:
    description: Allows reloading the Arrow core
    default: op