main: me.arrow.Core
name: ArrowLoader
version: 0.4.0
load: POSTWORLD
description: Loader for Arrow Anticheat (stel9178 on discord)
author: Stel
api-version: 1.13
softdepend:
  - PacketEvents
commands:
  arrowloader:
    description: ArrowLoader management commands.
    aliases: [al]
    permission: arrowloader.admin
  arrow:
    description: The main anticheat command!
  stuck:
    description: Teleport to spawn (Test Server Mode Only)

permissions:
  arrowloader.admin:
    description: Allows use of ArrowLoader commands and receives update notifications.
    default: op