main: me.arrow.Core
name: ArrowLoader
version: 0.3.1
load: POSTWORLD
description: Loader for Arrow Anticheat (stel9178 on discord)
author: Stel
api-version: 1.13
folia-supported: true
softdepend:
  - PacketEvents
commands:
  arrow:
    description: The main anticheat command!
  stuck:
    description: Teleport to spawn (Test Server Mode Only)